AWSTemplateFormatVersion: '2010-09-09'
Description: 'Build a vpc and a pair of EC2 instances across the a and b AZs'
Parameters:
  projectName:
    Description: "Project name to tag resources with using the ProjectName tag"
    Type: "String"
    MinLength: 1
    MaxLength: 255
    AllowedPattern: "^[a-zA-Z][-a-zA-Z0-9]*$"
    Default: "projectName"
  azA:
    Description: "Availability Zone A for the Region"
    Type: "AWS::EC2::AvailabilityZone::Name"
    Default: "Unknown"
  azB:
    Description: "Availability Zone B for the Region"
    Type: "AWS::EC2::AvailabilityZone::Name"
    Default: "Unknown"
Resources:
  vpc: {Type: 'AWS::EC2::VPC', Properties: {CidrBlock: 172.31.0.0/16, InstanceTenancy: default, EnableDnsSupport: 'true', EnableDnsHostnames: 'true', Tags: [{Key: ProjectName, Value: {Ref: projectName}}, {Key: Name, Value: {"Fn::Join": [ "-", [ Ref: projectName, "vpc" ] ]}}]}}
  subnetA: {Type: 'AWS::EC2::Subnet', Properties: {CidrBlock: 172.31.0.0/20, AvailabilityZone: {Ref: azA}, VpcId: {Ref: vpc}, Tags: [{Key: ProjectName, Value: {Ref: projectName}}, {Key: Name, Value: {"Fn::Join": [ "-", [ Ref: projectName, "subnetA" ] ]}}]}}
  subnetB: {Type: 'AWS::EC2::Subnet', Properties: {CidrBlock: 172.31.16.0/20, AvailabilityZone: {Ref: azB}, VpcId: {Ref: vpc}, Tags: [{Key: ProjectName, Value: {Ref: projectName}}, {Key: Name, Value: {"Fn::Join": [ "-", [ Ref: projectName, "subnetB" ] ]}}]}}
  ec2SecurityGroup:
    Type: 'AWS::EC2::SecurityGroup'
    Properties:
      GroupDescription: 'EC2 security group'
      VpcId:
        Ref: vpc
      Tags: [{Key: ProjectName, Value: {Ref: projectName}}, {Key: Name, Value: {"Fn::Join": [ "-", [ Ref: projectName, "ec2-sg" ] ]}}]
  loadBalancerSecurityGroup:
    Type: 'AWS::EC2::SecurityGroup'
    Properties:
      GroupDescription: 'Load balancer security group'
      VpcId:
        Ref: vpc
      Tags: [{Key: ProjectName, Value: {Ref: projectName}}, {Key: Name, Value: {"Fn::Join": [ "-", [ Ref: projectName, "lb-sg" ] ]}}]
  internetGateway: {Type: 'AWS::EC2::InternetGateway', Properties: {Tags: [{Key: ProjectName, Value: {Ref: projectName}}, {Key: Name, Value: {"Fn::Join": [ "-", [ Ref: projectName, "igw" ] ]}}]}}
  dhcpOptions: {Type: 'AWS::EC2::DHCPOptions', Properties: {DomainName: eu-west-1.compute.internal, DomainNameServers: [AmazonProvidedDNS]}}
  networkAcl: {Type: 'AWS::EC2::NetworkAcl', Properties: {VpcId: {Ref: vpc}}}
  routeTable: {Type: 'AWS::EC2::RouteTable', Properties: {VpcId: {Ref: vpc}}}
  acl1: {Type: 'AWS::EC2::NetworkAclEntry', Properties: {CidrBlock: 0.0.0.0/0, Egress: 'true', Protocol: '-1', RuleAction: allow, RuleNumber: '100', NetworkAclId: {Ref: networkAcl}}}
  acl2: {Type: 'AWS::EC2::NetworkAclEntry', Properties: {CidrBlock: 0.0.0.0/0, Protocol: '-1', RuleAction: allow, RuleNumber: '100', NetworkAclId: {Ref: networkAcl}}}
  subnetacl1: {Type: 'AWS::EC2::SubnetNetworkAclAssociation', Properties: {NetworkAclId: {Ref: networkAcl}, SubnetId: {Ref: subnetA}}}
  subnetacl2: {Type: 'AWS::EC2::SubnetNetworkAclAssociation', Properties: {NetworkAclId: {Ref: networkAcl}, SubnetId: {Ref: subnetB}}}
  gateway: {Type: 'AWS::EC2::VPCGatewayAttachment', Properties: {VpcId: {Ref: vpc}, InternetGatewayId: {Ref: internetGateway}}}
  subnetRouteA: {Type: 'AWS::EC2::SubnetRouteTableAssociation', Properties: {RouteTableId: {Ref: routeTable}, SubnetId: {Ref: subnetA}}}
  subnetRouteB: {Type: 'AWS::EC2::SubnetRouteTableAssociation', Properties: {RouteTableId: {Ref: routeTable}, SubnetId: {Ref: subnetB}}}
  route: {Type: 'AWS::EC2::Route', Properties: {DestinationCidrBlock: 0.0.0.0/0, RouteTableId: {Ref: routeTable}, GatewayId: {Ref: internetGateway}}, DependsOn: gateway}
  dhcpOptionsAssoc: {Type: 'AWS::EC2::VPCDHCPOptionsAssociation', Properties: {VpcId: {Ref: vpc}, DhcpOptionsId: {Ref: dhcpOptions}}}
Outputs:
  vpcId:
    Description: "VPC ID"
    Value: 
      Ref: vpc
    Export: 
      Name:
        "Fn::Sub": "${AWS::StackName}-vpcId"
  subnetA:
    Description: "The subnet ID for AZ A"
    Value: 
      Ref: subnetA
    Export:
      Name:
        "Fn::Sub": "${AWS::StackName}-subnetA"
  subnetB:
    Description: "The subnet ID for AZ B"
    Value:
      Ref: subnetB
    Export:
      Name:
        "Fn::Sub": "${AWS::StackName}-subnetB"
  ec2SecurityGroup:
    Description: "ec2 security group"
    Value:
      Ref: ec2SecurityGroup
    Export:
      Name:
        "Fn::Sub": "${AWS::StackName}-ec2SecurityGroup"
  loadBalancerSecurityGroup:
    Description: "load balancer security group"
    Value:
      Ref: loadBalancerSecurityGroup
    Export:
      Name:
        "Fn::Sub": "${AWS::StackName}-loadBalancerSecurityGroup"


