AWSTemplateFormatVersion: "2010-09-09"
Description: "RDS Aurora HA DB across AZ A and B"
Parameters:
  projectName:
    Description: "Project name to tag resources with using the ProjectName tag"
    Type: "String"
    MinLength: 1
    MaxLength: 255
    AllowedPattern: "^[a-zA-Z][-a-zA-Z0-9]*$"
    Default: "projectName"
  networkStackName:
    Description: "Name of the active network stack to reference for dependencies e.g. vpc"
    Type: "String"
    MinLength: 1
    MaxLength: 255
    AllowedPattern: "^[a-zA-Z][-a-zA-Z0-9]*$"
    Default: "networkStackName"
  ec2StackName:
    Description: "Name of the active ec2 stack to reference for dependencies e.g. rdsSecurityGroup"
    Type: "String"
    MinLength: 1
    MaxLength: 255
    AllowedPattern: "^[a-zA-Z][-a-zA-Z0-9]*$"
    Default: "ec2StackName"
  azRoot:
    Description: "Availability Zone root e.g. eu-west-1 - will be suffixed for each AZ used a,b,c, etc"
    Type: "String"
    Default: "Unknown"
  DBName:
    Default: MyDatabase
    Description: "The database name"
    Type: String
    MinLength: 1
    MaxLength: 64
    AllowedPattern: "[a-zA-Z][a-zA-Z0-9]*"
    ConstraintDescription: "must begin with a letter and contain only alphanumeric characters."
    Default: "ec2appdb"

Resources:
  auroraCluster:
    Type: "AWS::RDS::DBCluster"
    Properties:
      AvailabilityZones:
        - "Fn::Sub": "${azRoot}a"
        - "Fn::Sub": "${azRoot}b"
      DatabaseName:
        Ref: DBName
      DBClusterParameterGroupName:
        Ref: auroraParameterGroup
      DBSubnetGroupName:
        "Fn::ImportValue":
          "Fn::Sub": "${networkStackName}-dbSubnetGroup"
      Engine: aurora
      EngineVersion: 5.6
      MasterUsername: ec2appdbo
      MasterUserPassword: skylark123
      Port: 3306
      Tags: [{Key: ProjectName, Value: {Ref: projectName}}, {Key: Name, Value: {"Fn::Join": [ "-", [ Ref: projectName, "aurora-cluster" ] ]}}]
      VpcSecurityGroupIds:
        - "Fn::ImportValue":
            "Fn::Sub": "${ec2StackName}-rdsSecurityGroup"

  auroraParameterGroup:
    Type: "AWS::RDS::DBClusterParameterGroup"
    Properties:
      Description: "Aurora database cluster parameter group"
      Family: aurora5.6
      Parameters:
        time_zone: "UTC"
      Tags: [{Key: ProjectName, Value: {Ref: projectName}}, {Key: Name, Value: {"Fn::Join": [ "-", [ Ref: projectName, "aurora-pg" ] ]}}]

Outputs:
  MasterJDBCConnectionString:
    Description: "JDBC connection string for the master database"
    Value:
      "Fn::Join":
        - ""
        -
          - "jdbc:mysql://"
          - !GetAtt auroraCluster.Endpoint.Address
          - ":"
          - !GetAtt auroraCluster.Endpoint.Port
          - "/"
          - Ref: DBName
